<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemplateApp.Infrastructure\TemplateApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Requires a running Docker engine. -->
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>

</Project>
