<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\TemplateApp.Api\TemplateApp.Api.csproj" />
    <ProjectReference Include="..\TemplateApp.Tests.Common\TemplateApp.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Requires a running Docker engine. -->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

</Project>
